"use client";
/* eslint-disable @next/next/no-img-element */
import { useEffect, useMemo, useRef, useState, type PointerEvent } from "react";
import { CheckCircle2, Minus, Plus, RotateCcw } from "lucide-react";
import { Button } from "@/components/ui/button";
import { EditorToolbar } from "./editor-toolbar";
import { binarizeMask, containSize, type MaskTool, type Point, type Size } from "./mask-canvas";
type Props={imageUrl:string;maskUrl:string;confidence:number;onProcess:(mask?:Blob)=>void;onCancel?:()=>void;onRedetect?:()=>void|Promise<void>;busy?:boolean;message?:string};
export function MaskEditor({imageUrl,maskUrl,confidence,onProcess,onCancel,onRedetect,busy=false,message}:Props){
 const [tool,setTool]=useState<MaskTool>("paint"),[brush,setBrush]=useState(32),[zoom,setZoom]=useState(1),[pan,setPan]=useState<Point>({x:0,y:0}),[sourceSize,setSourceSize]=useState<Size>({width:0,height:0}),[stageSize,setStageSize]=useState<Size>({width:0,height:0}),[redetecting,setRedetecting]=useState(false);const stageRef=useRef<HTMLDivElement>(null),canvasRef=useRef<HTMLCanvasElement>(null),drawing=useRef(false),panning=useRef(false),lastPoint=useRef<Point|null>(null),panOrigin=useRef<Point|null>(null),history=useRef<ImageData[]>([]);const level=confidence>=.75?"alta":confidence>=.4?"média":"baixa",isBusy=busy||redetecting;
 const fittedSize=useMemo(()=>containSize(stageSize,sourceSize),[stageSize,sourceSize]);
 useEffect(()=>{const stage=stageRef.current;if(!stage)return;const measure=()=>setStageSize({width:stage.clientWidth,height:stage.clientHeight});measure();if(typeof ResizeObserver==="undefined")return;const observer=new ResizeObserver(([entry])=>setStageSize({width:entry.contentRect.width,height:entry.contentRect.height}));observer.observe(stage);return()=>observer.disconnect()},[]);
 useEffect(()=>{const canvas=canvasRef.current;if(!canvas)return;const image=new Image();image.src=maskUrl;image.onload=()=>{canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;const context=canvas.getContext("2d",{willReadFrequently:true});if(!context)return;context.globalCompositeOperation="source-over";context.drawImage(image,0,0);context.putImageData(binarizeMask(context.getImageData(0,0,canvas.width,canvas.height)),0,0);setSourceSize({width:image.naturalWidth,height:image.naturalHeight});history.current=[];setPan({x:0,y:0});setZoom(1)}},[maskUrl]);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key.toLowerCase()==="b")setTool("paint");if(event.key.toLowerCase()==="e")setTool("erase");if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="z"){event.preventDefault();const previous=history.current.pop();if(previous)canvasRef.current?.getContext("2d")?.putImageData(previous,0,0)}};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[]);
 function pointFromEvent(event:PointerEvent<HTMLCanvasElement>):Point{const canvas=canvasRef.current!,rect=canvas.getBoundingClientRect();return{x:(event.clientX-rect.left)*canvas.width/rect.width,y:(event.clientY-rect.top)*canvas.height/rect.height}}
 function draw(event:PointerEvent<HTMLCanvasElement>){if(tool==="pan"&&panning.current&&panOrigin.current){const next={x:event.clientX-panOrigin.current.x,y:event.clientY-panOrigin.current.y};setPan(current=>({x:current.x+next.x,y:current.y+next.y}));panOrigin.current={x:event.clientX,y:event.clientY};return}if(!drawing.current||tool==="pan")return;const canvas=canvasRef.current!,context=canvas.getContext("2d")!,point=pointFromEvent(event),previous=lastPoint.current??point;context.globalCompositeOperation="source-over";context.strokeStyle=tool==="erase"?"black":"white";context.fillStyle=context.strokeStyle;context.lineWidth=Math.max(1,brush);context.lineCap="round";context.lineJoin="round";context.beginPath();context.moveTo(previous.x,previous.y);context.lineTo(point.x,point.y);context.stroke();if(previous.x===point.x&&previous.y===point.y){context.beginPath();context.arc(point.x,point.y,Math.max(.5,brush/2),0,Math.PI*2);context.fill()}lastPoint.current=point}
 function begin(event:PointerEvent<HTMLCanvasElement>){const canvas=canvasRef.current!,context=canvas.getContext("2d")!;canvas.setPointerCapture(event.pointerId);if(tool==="pan"){panning.current=true;panOrigin.current={x:event.clientX,y:event.clientY};return}history.current.push(context.getImageData(0,0,canvas.width,canvas.height));if(history.current.length>20)history.current.shift();drawing.current=true;lastPoint.current=pointFromEvent(event);draw(event)}
 function end(event:PointerEvent<HTMLCanvasElement>){drawing.current=false;panning.current=false;lastPoint.current=null;panOrigin.current=null;if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId)}
 function submit(){const canvas=canvasRef.current;if(!canvas)return;const context=canvas.getContext("2d",{willReadFrequently:true});if(!context)return;context.putImageData(binarizeMask(context.getImageData(0,0,canvas.width,canvas.height)),0,0);canvas.toBlob(blob=>{if(blob)onProcess(blob)},"image/png")}
 async function redetect(){if(!onRedetect||isBusy)return;setRedetecting(true);try{await onRedetect()}finally{setRedetecting(false)}}
 function changeZoom(next:number){setZoom(Math.min(4,Math.max(.25,next)))}
 return <section className="editor-shell" data-testid="mask-editor" aria-busy={isBusy}><header className="editor-header"><div><span>Etapa 2 de 3</span><h2>Revise a área detectada</h2></div><div className={`confidence confidence-${level}`}><CheckCircle2 size={16}/> Confiança {level} · {Math.round(confidence*100)}%</div></header><div className="editor-grid"><EditorToolbar tool={tool} onTool={setTool}/><div ref={stageRef} className={`image-stage tool-${tool}`}><div className="image-transform" style={{width:fittedSize.width,height:fittedSize.height,left:`calc(50% + ${pan.x}px)`,top:`calc(50% + ${pan.y}px)`,transform:`translate(-50%, -50%) scale(${zoom})`}}><img src={imageUrl} alt="Imagem original para edição" draggable={false}/><canvas ref={canvasRef} className="mask-overlay" aria-label="Editar máscara; B pinta, E apaga e Ctrl+Z desfaz" tabIndex={0} onPointerDown={begin} onPointerMove={draw} onPointerUp={end} onPointerCancel={end}/></div><div className="zoom-controls" aria-label="Controle de zoom"><button type="button" aria-label="Diminuir zoom" onClick={()=>changeZoom(zoom-.25)} disabled={zoom<=.25}><Minus size={15}/></button><output aria-live="polite">{Math.round(zoom*100)}%</output><button type="button" aria-label="Aumentar zoom" onClick={()=>changeZoom(zoom+.25)} disabled={zoom>=4}><Plus size={15}/></button><button type="button" onClick={()=>{setZoom(1);setPan({x:0,y:0})}}>Ajustar</button></div></div><aside className="editor-controls"><div className="ai-notice"><strong>{level==="baixa"?"Revise manualmente":"Marca d'água encontrada"}</strong><p>A área em roxo será reconstruída. Use as ferramentas para corrigir.</p></div><label>Tamanho do pincel <output>{brush} px</output><input aria-label="Tamanho do pincel" type="range" min="1" max="96" step="1" value={brush} onChange={e=>setBrush(Number(e.target.value))}/></label><Button onClick={submit} disabled={isBusy}>{busy?"Reconstruindo…":"Remover marca d'água"}</Button>{busy&&<button className="text-action" onClick={onCancel}>Cancelar processamento</button>}<button className="text-action" onClick={redetect} disabled={isBusy||!onRedetect}><RotateCcw size={14}/> {redetecting?"Redetectando…":"Redetectar"}</button><p role="status">{message}</p></aside></div></section>}
